version: "3.8"
services:
    nextjs-app:
        build: .
        ports:
            - "80:3000"
            - "443:3000"
        environment:
            - NODE_ENV=development
        networks:
            - dokploy-network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend-app.rule=Host(`thenoteapp.com`)"
            - "traefik.http.routers.frontend-app.entrypoints=websecure"
            - "traefik.http.routers.frontend-app.tls.certResolver=letsencrypt"
  # Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    dokploy-network:
        external: true
