import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
    ColorSchemeScript,
    mantineHtmlProps,
    MantineProvider,
} from "@mantine/core";
import { theme } from "../theme";
import "./globals.css";
import "./editor.css";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { getSession } from "next-auth/react";
import { ReactNode } from "react";
import ClientSession from "./ClientSession";
import { auth } from "@/auth";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript defaultColorScheme="auto" />
                <link rel="shortcut icon" href="/favicon.svg" />
                <meta
                    name="viewport"
                    content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
                />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ServerSession>
                    <MantineProvider theme={theme} defaultColorScheme="auto">
                        <ReactQueryClientProvider>
                            {children}
                        </ReactQueryClientProvider>
                    </MantineProvider>
                </ServerSession>
            </body>
        </html>
    );
}

async function ServerSession({ children }: { children: ReactNode }) {
    const session = await auth();
    return <ClientSession session={session}>{children}</ClientSession>;
}
