"use client";

import {
    BlockquoteFigure,
    CharacterCount,
    CodeBlock,
    Color,
    Document,
    Dropcursor,
    Figcaption,
    Focus,
    FontFamily,
    FontSize,
    Heading,
    Highlight,
    HorizontalRule,
    ImageBlock,
    Link,
    Placeholder,
    Selection,
    SlashCommand,
    StarterKit,
    Subscript,
    Superscript,
    Table,
    TableCell,
    TableHeader,
    TableRow,
    TextAlign,
    TextStyle,
    TrailingNode,
    Typography,
    Underline,
    Columns,
    Column,
    TaskItem,
    TaskList,
    UniqueID,
    ImageUpload,
    Figure,
} from "./";

import { isChangeOrigin } from "@tiptap/extension-collaboration";

export const ExtensionKit = () => [
    Document,
    Columns,
    TaskList,
    TaskItem.configure({
        nested: true,
    }),
    Column,
    Selection,
    Heading.configure({
        levels: [1, 2, 3, 4, 5, 6],
    }),
    HorizontalRule,
    UniqueID.configure({
        types: ["paragraph", "heading", "blockquote", "codeBlock", "table"],
        filterTransaction: (transaction) => !isChangeOrigin(transaction),
    }),
    StarterKit.configure({
        document: false,
        dropcursor: false,
        heading: false,
        horizontalRule: false,
        blockquote: false,
        history: false,
        codeBlock: false,
    }),
    CodeBlock,
    TextStyle,
    TextAlign,
    FontSize,
    FontFamily,
    Color,
    TrailingNode,
    Link.configure({
        openOnClick: false,
    }),
    Highlight.configure({ multicolor: true }),
    Underline,
    CharacterCount.configure({ limit: 50000 }),
    // ImageBlock,
    // ImageUpload.configure({}),
    Subscript,
    Superscript,
    Table,
    TableCell,
    TableHeader,
    TableRow,
    Typography,
    Placeholder.configure({
        includeChildren: true,
        showOnlyCurrent: false,
        placeholder: () => "",
    }),
    SlashCommand,
    Focus,
    Figure,
    // Figcaption,
    BlockquoteFigure,
    Dropcursor.configure({
        width: 2,
        class: "ProseMirror-dropcursor border-black",
    }),
];

export default ExtensionKit;
