/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        /** @description Refresh token cookie (HttpOnly, Secure) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using refresh cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Refreshed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and clear refresh cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces I belong to */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Workspace"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create workspace */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspaceCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workspace"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read workspace */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["WorkspaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workspace"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update workspace */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["WorkspaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspacePatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workspace"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List memories with filters */
        get: {
            parameters: {
                query: {
                    workspace_id: components["parameters"]["WorkspaceIdQuery"];
                    q?: components["parameters"]["Q"];
                    tag?: components["parameters"]["Tag"];
                    kind?: components["parameters"]["Kind"];
                    from?: components["parameters"]["From"];
                    to?: components["parameters"]["To"];
                    limit?: components["parameters"]["Limit"];
                    cursor?: components["parameters"]["Cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create (capture) memory */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description Version tag for concurrency control */
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Memory"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read memory by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["MemoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Memory"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Soft delete (archive) memory */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["MemoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update memory (JSON Merge Patch) */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Provide ETag for optimistic concurrency */
                    "If-Match"?: string;
                };
                path: {
                    id: components["parameters"]["MemoryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/merge-patch+json": components["schemas"]["MemoryPatch"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Memory"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/memories/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List comments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["MemoryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Comment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Add comment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["MemoryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memories/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace memory tags (idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["MemoryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tags?: string[];
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Memory"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags in a workspace (prefix match) */
        get: {
            parameters: {
                query: {
                    workspace_id: components["parameters"]["WorkspaceIdQuery"];
                    prefix?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Tag"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create or upsert tag */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tag"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate presigned upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssetUploadInit"];
                };
            };
            responses: {
                /** @description Upload initiated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetUploadInitResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize uploaded asset (scan + metadata) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    asset_id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Finalized asset */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get asset metadata (and optionally a signed URL) */
        get: {
            parameters: {
                query?: {
                    signed_url?: boolean;
                };
                header?: never;
                path: {
                    asset_id: components["parameters"]["AssetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search memories (basic text + filters) */
        get: {
            parameters: {
                query: {
                    workspace_id: components["parameters"]["WorkspaceIdQuery"];
                    q?: components["parameters"]["Q"];
                    tag?: components["parameters"]["Tag"];
                    kind?: components["parameters"]["Kind"];
                    from?: components["parameters"]["From"];
                    to?: components["parameters"]["To"];
                    limit?: components["parameters"]["Limit"];
                    cursor?: components["parameters"]["Cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/generate-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a concise title from blocks */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        blocks?: components["schemas"]["MemoryBlock"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            title?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summarize a memory or provided blocks */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        memory_id?: string;
                        blocks?: components["schemas"]["MemoryBlock"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (DB/migrations) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            access_token: string;
            /** @default Bearer */
            token_type: string;
            /** @example 3600 */
            expires_in?: number;
        };
        User: {
            id?: string;
            /** Format: email */
            email?: string;
            name?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Workspace: {
            id: string;
            name: string;
            icon?: string | null;
            owner_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        WorkspaceCreate: {
            name: string;
            icon?: string | null;
        };
        WorkspacePatch: {
            name?: string;
            icon?: string | null;
        };
        /** @enum {string} */
        MemoryKind: "note" | "link" | "code" | "file" | "image" | "highlight" | "quote";
        Memory: {
            id: string;
            workspace_id: string;
            kind: components["schemas"]["MemoryKind"];
            title?: string | null;
            tags?: string[];
            /** @description Either parent_id is set or this memory is a root capture. */
            provenance?: {
                parent_id?: string | null;
                /** @default false */
                is_root: boolean;
            };
            blocks: components["schemas"]["MemoryBlock"][];
            created_by?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        MemoryCreate: {
            workspace_id: string;
            kind: components["schemas"]["MemoryKind"];
            title?: string | null;
            provenance?: {
                parent_id?: string | null;
            };
            blocks: components["schemas"]["MemoryBlock"][];
            tags?: string[];
        };
        /** @description JSON Merge Patch shape */
        MemoryPatch: {
            title?: string | null;
            provenance?: {
                parent_id?: string | null;
                is_root?: boolean;
            };
            blocks?: components["schemas"]["MemoryBlock"][];
            tags?: string[];
        };
        MemoryBlock: {
            id?: string | null;
            /** @enum {string} */
            type: "text" | "link" | "code" | "file" | "image" | "quote" | "highlight";
        } & ({
            /** @enum {string} */
            type?: "text";
            text: string;
        } | {
            /** @enum {string} */
            type?: "link";
            /** Format: uri */
            url: string;
        } | {
            /** @enum {string} */
            type?: "code";
            language: string;
            code: string;
        } | {
            /** @enum {string} */
            type?: "file";
            asset_id: string;
            name?: string | null;
        } | {
            /** @enum {string} */
            type?: "image";
            asset_id: string;
        } | {
            /** @enum {string} */
            type?: "quote";
            text: string;
            source?: string | null;
        } | {
            /** @enum {string} */
            type?: "highlight";
            text: string;
            /** Format: uri */
            source_url?: string | null;
        });
        MemoryListResponse: {
            data?: components["schemas"]["Memory"][];
            next_cursor?: string | null;
        };
        Comment: {
            id: string;
            memory_id: string;
            author_id: string;
            text: string;
            /** Format: date-time */
            created_at: string;
        };
        CommentCreate: {
            text: string;
        };
        Tag: {
            id: string;
            workspace_id: string;
            name: string;
        };
        TagCreate: {
            workspace_id: string;
            name: string;
        };
        /** @enum {string} */
        AssetStatus: "pending" | "uploaded" | "finalized" | "failed";
        Asset: {
            id: string;
            workspace_id: string;
            /** @enum {string} */
            kind: "file" | "image";
            mime?: string;
            size?: number;
            sha256?: string;
            status: components["schemas"]["AssetStatus"];
            /** Format: uri */
            signed_url?: string | null;
            created_by?: string;
            /** Format: date-time */
            created_at?: string;
        };
        AssetUploadInit: {
            workspace_id: string;
            /** @enum {string} */
            kind: "file" | "image";
            mime: string;
            size: number;
        };
        AssetUploadInitResponse: {
            asset_id: string;
            /** Format: uri */
            upload_url: string;
            headers?: {
                [key: string]: string;
            };
        };
        SearchHit: {
            memory: components["schemas"]["Memory"];
            highlight?: string;
        };
        SearchResponse: {
            data?: components["schemas"]["SearchHit"][];
            next_cursor?: string | null;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        WorkspaceId: string;
        WorkspaceIdQuery: string;
        MemoryId: string;
        AssetId: string;
        Q: string;
        Tag: string;
        Kind: components["schemas"]["MemoryKind"];
        From: string;
        To: string;
        Limit: number;
        Cursor: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
